Fin de chap 6:[ADD]
gracektassi/mytraining pull request #4
Opened 2024-10-18 11:38 UTC by gracektassi

FIN CHAP 6: J'AI AJOUTE LES SEARCH VIEWS dans  le fichier estate_property_views.xml

2024-10-18 12:14 UTC, kfr-odoo requested changes

2024-10-18 12:14 UTC, kfr-odoo commented on estate/models/estate_property.py
> +        return fields.Date.context_today(self)
Pourquoi ce changement ?

2024-10-18 12:14 UTC, kfr-odoo commented on estate/models/estate_property.py
> +    User_Id = fields.Char("Postcode")
snake_case
Et "Postcode" ne me semble pas être une valeure appropriée ni le type `fields.Char`
Exemple:
```suggestion

    user_Id = fields.Many2one("res.users", string="Seller")    
```

2024-10-20 19:43 UTC, gracektassi commented on estate/models/estate_property.py
> +        return fields.Date.context_today(self)
C'est juste pour changer la date par DEFAUT; mais je peux retourner l'ancien si NECESSAIRE
```suggestion
        return fields.Date.context_today(self) + relativedelta(months=3)
```

2024-10-20 19:43 UTC, gracektassi commented on estate/models/estate_property.py
> +    User_Id = fields.Char("Postcode")
D'ACCORD JE VOIS MERCI!

2024-10-21 07:34 UTC, kfr-odoo approved these changes

2024-10-21 13:51 UTC, merged